# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/geckodev/Desktop/NuGASP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/geckodev/Desktop/NuGASP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/geckodev/Desktop/NuGASP/CMakeFiles /home/geckodev/Desktop/NuGASP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/geckodev/Desktop/NuGASP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QTCanvasDemo

# Build rule for target.
QTCanvasDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QTCanvasDemo
.PHONY : QTCanvasDemo

# fast build rule for target.
QTCanvasDemo/fast:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/build
.PHONY : QTCanvasDemo/fast

#=============================================================================
# Target rules for targets named QTCanvasDemo_autogen

# Build rule for target.
QTCanvasDemo_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QTCanvasDemo_autogen
.PHONY : QTCanvasDemo_autogen

# fast build rule for target.
QTCanvasDemo_autogen/fast:
	$(MAKE) -f CMakeFiles/QTCanvasDemo_autogen.dir/build.make CMakeFiles/QTCanvasDemo_autogen.dir/build
.PHONY : QTCanvasDemo_autogen/fast

QTCanvasDemo_autogen/mocs_compilation.o: QTCanvasDemo_autogen/mocs_compilation.cpp.o

.PHONY : QTCanvasDemo_autogen/mocs_compilation.o

# target to build an object file
QTCanvasDemo_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/QTCanvasDemo_autogen/mocs_compilation.cpp.o
.PHONY : QTCanvasDemo_autogen/mocs_compilation.cpp.o

QTCanvasDemo_autogen/mocs_compilation.i: QTCanvasDemo_autogen/mocs_compilation.cpp.i

.PHONY : QTCanvasDemo_autogen/mocs_compilation.i

# target to preprocess a source file
QTCanvasDemo_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/QTCanvasDemo_autogen/mocs_compilation.cpp.i
.PHONY : QTCanvasDemo_autogen/mocs_compilation.cpp.i

QTCanvasDemo_autogen/mocs_compilation.s: QTCanvasDemo_autogen/mocs_compilation.cpp.s

.PHONY : QTCanvasDemo_autogen/mocs_compilation.s

# target to generate assembly for a file
QTCanvasDemo_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/QTCanvasDemo_autogen/mocs_compilation.cpp.s
.PHONY : QTCanvasDemo_autogen/mocs_compilation.cpp.s

include/moc_mainwindow.o: include/moc_mainwindow.cpp.o

.PHONY : include/moc_mainwindow.o

# target to build an object file
include/moc_mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/include/moc_mainwindow.cpp.o
.PHONY : include/moc_mainwindow.cpp.o

include/moc_mainwindow.i: include/moc_mainwindow.cpp.i

.PHONY : include/moc_mainwindow.i

# target to preprocess a source file
include/moc_mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/include/moc_mainwindow.cpp.i
.PHONY : include/moc_mainwindow.cpp.i

include/moc_mainwindow.s: include/moc_mainwindow.cpp.s

.PHONY : include/moc_mainwindow.s

# target to generate assembly for a file
include/moc_mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/include/moc_mainwindow.cpp.s
.PHONY : include/moc_mainwindow.cpp.s

include/moc_plotwindow.o: include/moc_plotwindow.cpp.o

.PHONY : include/moc_plotwindow.o

# target to build an object file
include/moc_plotwindow.cpp.o:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/include/moc_plotwindow.cpp.o
.PHONY : include/moc_plotwindow.cpp.o

include/moc_plotwindow.i: include/moc_plotwindow.cpp.i

.PHONY : include/moc_plotwindow.i

# target to preprocess a source file
include/moc_plotwindow.cpp.i:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/include/moc_plotwindow.cpp.i
.PHONY : include/moc_plotwindow.cpp.i

include/moc_plotwindow.s: include/moc_plotwindow.cpp.s

.PHONY : include/moc_plotwindow.s

# target to generate assembly for a file
include/moc_plotwindow.cpp.s:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/include/moc_plotwindow.cpp.s
.PHONY : include/moc_plotwindow.cpp.s

include/moc_qtcanvas.o: include/moc_qtcanvas.cpp.o

.PHONY : include/moc_qtcanvas.o

# target to build an object file
include/moc_qtcanvas.cpp.o:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/include/moc_qtcanvas.cpp.o
.PHONY : include/moc_qtcanvas.cpp.o

include/moc_qtcanvas.i: include/moc_qtcanvas.cpp.i

.PHONY : include/moc_qtcanvas.i

# target to preprocess a source file
include/moc_qtcanvas.cpp.i:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/include/moc_qtcanvas.cpp.i
.PHONY : include/moc_qtcanvas.cpp.i

include/moc_qtcanvas.s: include/moc_qtcanvas.cpp.s

.PHONY : include/moc_qtcanvas.s

# target to generate assembly for a file
include/moc_qtcanvas.cpp.s:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/include/moc_qtcanvas.cpp.s
.PHONY : include/moc_qtcanvas.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o

.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i

.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s

.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/plotwindow.o: src/plotwindow.cpp.o

.PHONY : src/plotwindow.o

# target to build an object file
src/plotwindow.cpp.o:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/src/plotwindow.cpp.o
.PHONY : src/plotwindow.cpp.o

src/plotwindow.i: src/plotwindow.cpp.i

.PHONY : src/plotwindow.i

# target to preprocess a source file
src/plotwindow.cpp.i:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/src/plotwindow.cpp.i
.PHONY : src/plotwindow.cpp.i

src/plotwindow.s: src/plotwindow.cpp.s

.PHONY : src/plotwindow.s

# target to generate assembly for a file
src/plotwindow.cpp.s:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/src/plotwindow.cpp.s
.PHONY : src/plotwindow.cpp.s

src/qtcanvas.o: src/qtcanvas.cpp.o

.PHONY : src/qtcanvas.o

# target to build an object file
src/qtcanvas.cpp.o:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/src/qtcanvas.cpp.o
.PHONY : src/qtcanvas.cpp.o

src/qtcanvas.i: src/qtcanvas.cpp.i

.PHONY : src/qtcanvas.i

# target to preprocess a source file
src/qtcanvas.cpp.i:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/src/qtcanvas.cpp.i
.PHONY : src/qtcanvas.cpp.i

src/qtcanvas.s: src/qtcanvas.cpp.s

.PHONY : src/qtcanvas.s

# target to generate assembly for a file
src/qtcanvas.cpp.s:
	$(MAKE) -f CMakeFiles/QTCanvasDemo.dir/build.make CMakeFiles/QTCanvasDemo.dir/src/qtcanvas.cpp.s
.PHONY : src/qtcanvas.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... QTCanvasDemo"
	@echo "... QTCanvasDemo_autogen"
	@echo "... QTCanvasDemo_autogen/mocs_compilation.o"
	@echo "... QTCanvasDemo_autogen/mocs_compilation.i"
	@echo "... QTCanvasDemo_autogen/mocs_compilation.s"
	@echo "... include/moc_mainwindow.o"
	@echo "... include/moc_mainwindow.i"
	@echo "... include/moc_mainwindow.s"
	@echo "... include/moc_plotwindow.o"
	@echo "... include/moc_plotwindow.i"
	@echo "... include/moc_plotwindow.s"
	@echo "... include/moc_qtcanvas.o"
	@echo "... include/moc_qtcanvas.i"
	@echo "... include/moc_qtcanvas.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/plotwindow.o"
	@echo "... src/plotwindow.i"
	@echo "... src/plotwindow.s"
	@echo "... src/qtcanvas.o"
	@echo "... src/qtcanvas.i"
	@echo "... src/qtcanvas.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

